### ISSUE TITLE
curl-config -tfrc not working

### ISSUE THREAD

**Issue by mengesb** [hashicorp-community/tf-helper#10] opened 2019-08-06 17:59 UTC
I'm trying to generate the curl-config using the command line `tfh curl-config -tfrc` and I'm getting:

```text
[ERROR] unable to extract token from terraformrc:
[ERROR] /Users/<username>/.terraformrc
```

Here's the debug log:

```text
org:       
prefix:    
workspace: 
hostname:  <wrong fqdn>
address:   https://<wrong fqdn>
verbose:   1
vverbose:  1
vvverbose: 1
token:     empty, unused
curlrc:    /Users/<username>/.tfh/curlrc
[ERROR] unable to extract token from terraformrc:
[ERROR] /Users/<username>/.terraformrc
```

My ~/.terraformrc has the correct content for hostname and token... so I'm not sure what its problem is. It certainly isn't reading the terraformrc from what I can see, but file permissions are fine.

**Comment by mengesb** [comment] 2019-08-07 00:38
Since the `~/.terraform.rc` contains a header identifying the hostname, it should parse the hostname from that field to generate the curlrc file.

**Comment by mengesb** [comment] 2019-08-07 00:39
I've since resolved my own problem specifying `-hostname <host>` but either documentation needs to call this out or parse it from the `~/.terraformrc` file

**Comment by fprimex** [comment] 2019-08-08 14:07
Hi, thanks for the report. This does seem like an oversight in not accounting for private instances when generating the curl config. How were you specifying the hostname previously for other commands, if not by `-hostname`? Was the `<wrong fqdn>` `app.terraform.io` (the SaaS)?

**Comment by fprimex** [comment] 2020-01-06 23:42
I looked over this, and I'd say the behavior described is by design, in that the `.terraformrc` file can have multiple keys in it, and, like `terraform`, `tfh` can operate on multiple instances, with the default `app.terraform.io`.

That said, `tfh` is about convenience and good usability. I've merged into master a change so that if there is only one token it will use that one, even if `hostname` does not match the `credentials` host. So:

* If there's one token, use that one.
* If there's more than one and a host matches, use the matching token.
* If there are none found or there's more than one with no host match, error.

This will be included in the next release.

**Closed as completed by fprimex** 2020-01-06 23:42 UTC
